export const ENROLLMENT_STATUS_MAYBE = 'MAYBE';
export const ENROLLMENT_STATUS_NO = 'NO';
export const ENROLLMENT_STATUS_YES = 'YES';

export const ENROLLMENT_STATUS_STRING = {
  [ENROLLMENT_STATUS_MAYBE]: 'Unsure',
  [ENROLLMENT_STATUS_NO]: 'Not going',
  [ENROLLMENT_STATUS_YES]: 'Going'
};

export const ENROLLMENT_STATUSES = [
  ENROLLMENT_STATUS_YES,
  ENROLLMENT_STATUS_MAYBE,
  ENROLLMENT_STATUS_NO
];
